<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title>Including contextual information with error chains — topic-error-chaining • rlang</title><!-- favicons --><link rel="icon" type="image/png" sizes="96x96" href="../favicon-96x96.png"><link rel="icon" type="”image/svg+xml”" href="../favicon.svg"><link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png"><link rel="icon" sizes="any" href="../favicon.ico"><link rel="manifest" href="../site.webmanifest"><script src="../deps/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><link href="../deps/bootstrap-5.3.1/bootstrap.min.css" rel="stylesheet"><script src="../deps/bootstrap-5.3.1/bootstrap.bundle.min.js"></script><link href="../deps/Source_Sans_Pro-0.4.10/font.css" rel="stylesheet"><link href="../deps/Source_Code_Pro-0.4.10/font.css" rel="stylesheet"><link href="../deps/font-awesome-6.5.2/css/all.min.css" rel="stylesheet"><link href="../deps/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet"><script src="../deps/headroom-0.11.0/headroom.min.js"></script><script src="../deps/headroom-0.11.0/jQuery.headroom.min.js"></script><script src="../deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js"></script><script src="../deps/clipboard.js-2.0.11/clipboard.min.js"></script><script src="../deps/search-1.0.0/autocomplete.jquery.min.js"></script><script src="../deps/search-1.0.0/fuse.min.js"></script><script src="../deps/search-1.0.0/mark.min.js"></script><!-- pkgdown --><script src="../pkgdown.js"></script><meta property="og:title" content="Including contextual information with error chains — topic-error-chaining"><meta name="description" content='Error chaining is a mechanism for providing contextual information when an error occurs. There are multiple situations in which you might be able to provide context that is helpful to quickly understand the cause or origin of an error:
Mentioning the high level context in which a low level error arose. E.g. chaining a low-level HTTP error to a high-level download error.
Mentioning the pipeline step in which a user error occurred. This is a major use-case for NSE interfaces in the tidyverse, e.g. in dplyr, tidymodels or ggplot2.
Mentioning the iteration context in which a user error occurred. For instance, the input file when processing documents, or the iteration number or key when running user code in a loop.


Here is an example of a chained error from dplyr that shows the pipeline step (mutate()) and the iteration context (group ID) in which a function called by the user failed:
add &amp;lt;- function(x, y) x + y

mtcars |&amp;gt;
  dplyr::group_by(cyl) |&amp;gt;
  dplyr::mutate(new = add(disp, "foo"))
#&amp;gt; Error in `dplyr::mutate()`:
#&amp;gt; i In argument: `new = add(disp, "foo")`.
#&amp;gt; i In group 1: `cyl = 4`.
#&amp;gt; Caused by error in `x + y`:
#&amp;gt; ! non-numeric argument to binary operator

In all these cases, there are two errors in play, chained together:
The causal error, which interrupted the current course of action.
The contextual error, which expresses higher-level information when something goes wrong.


There may be more than one contextual error in an error chain, but there is always only one causal error.'><meta property="og:description" content='Error chaining is a mechanism for providing contextual information when an error occurs. There are multiple situations in which you might be able to provide context that is helpful to quickly understand the cause or origin of an error:
Mentioning the high level context in which a low level error arose. E.g. chaining a low-level HTTP error to a high-level download error.
Mentioning the pipeline step in which a user error occurred. This is a major use-case for NSE interfaces in the tidyverse, e.g. in dplyr, tidymodels or ggplot2.
Mentioning the iteration context in which a user error occurred. For instance, the input file when processing documents, or the iteration number or key when running user code in a loop.


Here is an example of a chained error from dplyr that shows the pipeline step (mutate()) and the iteration context (group ID) in which a function called by the user failed:
add &amp;lt;- function(x, y) x + y

mtcars |&amp;gt;
  dplyr::group_by(cyl) |&amp;gt;
  dplyr::mutate(new = add(disp, "foo"))
#&amp;gt; Error in `dplyr::mutate()`:
#&amp;gt; i In argument: `new = add(disp, "foo")`.
#&amp;gt; i In group 1: `cyl = 4`.
#&amp;gt; Caused by error in `x + y`:
#&amp;gt; ! non-numeric argument to binary operator

In all these cases, there are two errors in play, chained together:
The causal error, which interrupted the current course of action.
The contextual error, which expresses higher-level information when something goes wrong.


There may be more than one contextual error in an error chain, but there is always only one causal error.'><meta property="og:image" content="https://rlang.r-lib.org/logo.png"><meta name="robots" content="noindex"><script src="https://cdn.jsdelivr.net/gh/posit-dev/supported-by-posit/js/badge.min.js" data-hide-below="1200" data-max-height="43" data-light-bg="#666f76" data-light-fg="#f9f9f9"></script><script defer data-domain="rlang.r-lib.org,all.tidyverse.org" src="https://plausible.io/js/plausible.js"></script></head><body>
    <a href="#container" class="visually-hidden-focusable">Skip to content</a>


    <nav class="navbar navbar-expand-lg fixed-top bg-none" data-bs-theme="light" aria-label="Site navigation"><div class="container">

    <a class="navbar-brand me-2" href="../index.html">rlang</a>

    <small class="nav-text text-danger me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="In-development version">1.1.6.9000</small>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar" class="collapse navbar-collapse ms-3">
      <ul class="navbar-nav me-auto"><li class="nav-item"><a class="nav-link" href="../reference/index.html">Reference</a></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-tidy-evaluation" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Tidy evaluation</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-tidy-evaluation"><li><h6 class="dropdown-header" data-toc-skip>Overviews</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-data-mask.html">What is data-masking and why do I need `{{`?</a></li>
    <li><a class="dropdown-item" href="../reference/topic-data-mask-programming.html">Data mask programming patterns</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Guides</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-data-mask-ambiguity.html">The data mask ambiguity</a></li>
    <li><a class="dropdown-item" href="../reference/topic-double-evaluation.html">The double evaluation problem</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Notes</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-inject-out-of-context.html">What happens if I use injection operators out of context?</a></li>
    <li><a class="dropdown-item" href="../reference/topic-embrace-non-args.html">Does `{{` work on regular objects?</a></li>
  </ul></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-metaprogramming" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Metaprogramming</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-metaprogramming"><li><h6 class="dropdown-header" data-toc-skip>Overviews</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-defuse.html">Defusing R expressions</a></li>
    <li><a class="dropdown-item" href="../reference/topic-inject.html">Injecting with `!!`, `!!!`, and glue syntax</a></li>
    <li><a class="dropdown-item" href="../reference/topic-metaprogramming.html">Metaprogramming patterns</a></li>
    <li><a class="dropdown-item" href="../reference/topic-quosure.html">What are quosures and when are they needed?</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Guides</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-multiple-columns.html">Taking multiple columns without `...`</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Notes</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-embrace-constants.html">Why are strings and other constants enquosed in the empty environment?</a></li>
  </ul></li>
<li class="active nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-conditions" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Conditions</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-conditions"><li><h6 class="dropdown-header" data-toc-skip>Guides</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-error-call.html">Including function calls in error messages</a></li>
    <li><a class="dropdown-item" href="../reference/topic-error-chaining.html">Including contextual information with error chains</a></li>
    <li><a class="dropdown-item" href="../reference/topic-condition-formatting.html">Formatting messages with cli</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><h6 class="dropdown-header" data-toc-skip>Notes</h6></li>
    <li><a class="dropdown-item" href="../reference/topic-condition-customisation.html">Customising condition messages</a></li>
  </ul></li>
<li class="nav-item dropdown">
  <button class="nav-link dropdown-toggle" type="button" id="dropdown-news" data-bs-toggle="dropdown" aria-expanded="false" aria-haspopup="true">News</button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-news"><li><h6 class="dropdown-header" data-toc-skip>Releases</h6></li>
    <li><a class="external-link dropdown-item" href="https://www.tidyverse.org/blog/2020/02/glue-strings-and-tidy-eval/">Version 0.4.3</a></li>
    <li><a class="external-link dropdown-item" href="https://www.tidyverse.org/articles/2019/06/rlang-0-4-0/">Version 0.4.0</a></li>
    <li><a class="external-link dropdown-item" href="https://www.tidyverse.org/articles/2019/01/rlang-0-3-1/">Version 0.3.1</a></li>
    <li><a class="external-link dropdown-item" href="https://www.tidyverse.org/articles/2018/10/rlang-0-3-0/">Version 0.3.0</a></li>
    <li><a class="external-link dropdown-item" href="https://www.tidyverse.org/articles/2018/03/rlang-0.2.0/">Version 0.2.0</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="../news/index.html">Changelog</a></li>
  </ul></li>
      </ul><ul class="navbar-nav"><li class="nav-item"><form class="form-inline" role="search">
 <input class="form-control" type="search" name="search-input" id="search-input" autocomplete="off" aria-label="Search site" placeholder="Search for" data-search-index="../search.json"></form></li>
<li class="nav-item"><a class="external-link nav-link" href="https://github.com/r-lib/rlang/" aria-label="GitHub"><span class="fa fab fa-github fa-lg"></span></a></li>
      </ul></div>


  </div>
</nav><div class="container template-reference-topic" id="container">
<div class="row">
  <main id="main" class="col-md-9"><div class="page-header">
      <img src="../logo.png" class="logo" alt=""><h1>Including contextual information with error chains</h1>
      <small class="dont-index">Source: <a href="https://github.com/r-lib/rlang/blob/main/R/topic-errors.R" class="external-link"><code>R/topic-errors.R</code></a></small>
      <div class="d-none name"><code>topic-error-chaining.Rd</code></div>
    </div>

    <div class="ref-description section level2">
    <p>Error chaining is a mechanism for providing contextual information when an error occurs. There are multiple situations in which you might be able to provide context that is helpful to quickly understand the cause or origin of an error:</p><ul><li><p>Mentioning the <em>high level context</em> in which a low level error arose. E.g. chaining a low-level HTTP error to a high-level download error.</p></li>
<li><p>Mentioning the <em>pipeline step</em> in which a user error occurred. This is a major use-case for NSE interfaces in the tidyverse, e.g. in dplyr, tidymodels or ggplot2.</p></li>
<li><p>Mentioning the <em>iteration context</em> in which a user error occurred. For instance, the input file when processing documents, or the iteration number or key when running user code in a loop.</p></li>
</ul><p>Here is an example of a chained error from dplyr that shows the pipeline step (<code>mutate()</code>) and the iteration context (group ID) in which a function called by the user failed:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">add</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span><span class="op">)</span> <span class="va">x</span> <span class="op">+</span> <span class="va">y</span></span>
<span></span>
<span><span class="va">mtcars</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html" class="external-link">group_by</a></span><span class="op">(</span><span class="va">cyl</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html" class="external-link">mutate</a></span><span class="op">(</span>new <span class="op">=</span> <span class="fu">add</span><span class="op">(</span><span class="va">disp</span>, <span class="st">"foo"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `dplyr::mutate()`:</span></span>
<span><span class="co">#&gt; i In argument: `new = add(disp, "foo")`.</span></span>
<span><span class="co">#&gt; i In group 1: `cyl = 4`.</span></span>
<span><span class="co">#&gt; Caused by error in `x + y`:</span></span>
<span><span class="co">#&gt; ! non-numeric argument to binary operator</span></span></code></pre><p></p></div>
<p>In all these cases, there are two errors in play, chained together:</p><ol><li><p>The <strong>causal error</strong>, which interrupted the current course of action.</p></li>
<li><p>The <strong>contextual error</strong>, which expresses higher-level information when something goes wrong.</p></li>
</ol><p>There may be more than one contextual error in an error chain, but there is always only one causal error.</p>
    </div>


    <div class="section level2">
    <h2 id="rethrowing-errors">Rethrowing errors<a class="anchor" aria-label="anchor" href="#rethrowing-errors"></a></h2>
    <p>To create an error chain, you must first capture causal errors when they occur. We recommend using <code><a href="try_fetch.html">try_fetch()</a></code> instead of <code><a href="https://rdrr.io/r/base/conditions.html" class="external-link">tryCatch()</a></code> or <code><a href="https://rdrr.io/r/base/conditions.html" class="external-link">withCallingHandlers()</a></code>.</p><ul><li><p>Compared to <code><a href="https://rdrr.io/r/base/conditions.html" class="external-link">tryCatch()</a></code>, <code><a href="try_fetch.html">try_fetch()</a></code> fully preserves the context of the error. This is important for debugging because it ensures complete backtraces are reported to users (e.g. via <code><a href="last_error.html">last_error()</a></code>) and allows <code>options(error = recover)</code> to reach into the deepest error context.</p></li>
<li><p>Compared to <code><a href="https://rdrr.io/r/base/conditions.html" class="external-link">withCallingHandlers()</a></code>, which also preserves the error context, <code><a href="try_fetch.html">try_fetch()</a></code> is able to catch stack overflow errors on R versions &gt;= 4.2.0.</p></li>
</ul><p>In practice, <code><a href="try_fetch.html">try_fetch()</a></code> works just like <code><a href="https://rdrr.io/r/base/conditions.html" class="external-link">tryCatch()</a></code>. It takes pairs of error class names and handling functions. To chain an error, simply rethrow it from an error handler by passing it as <code>parent</code> argument.</p>
<p>In this example, we'll create a <code>with_</code> function. That is, a function that sets up some configuration (in this case, chained errors) before executing code supplied as input:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">with_chained_errors</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">expr</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="../reference/try_fetch.html">try_fetch</a></span><span class="op">(</span></span>
<span>    <span class="va">expr</span>,</span>
<span>    error <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">cnd</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="fu"><a href="../reference/abort.html">abort</a></span><span class="op">(</span><span class="st">"Problem during step."</span>, parent <span class="op">=</span> <span class="va">cnd</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu">with_chained_errors</span><span class="op">(</span><span class="fl">1</span> <span class="op">+</span> <span class="st">""</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `with_chained_errors()`:</span></span>
<span><span class="co">#&gt; ! Problem during step.</span></span>
<span><span class="co">#&gt; Caused by error in `1 + ""`:</span></span>
<span><span class="co">#&gt; ! non-numeric argument to binary operator</span></span></code></pre><p></p></div>
<p>Typically, you'll use this error helper from another user-facing function.</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">my_verb</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">expr</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu">with_chained_errors</span><span class="op">(</span><span class="va">expr</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu">my_verb</span><span class="op">(</span><span class="fu">add</span><span class="op">(</span><span class="fl">1</span>, <span class="st">""</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `with_chained_errors()`:</span></span>
<span><span class="co">#&gt; ! Problem during step.</span></span>
<span><span class="co">#&gt; Caused by error in `x + y`:</span></span>
<span><span class="co">#&gt; ! non-numeric argument to binary operator</span></span></code></pre><p></p></div>
<p>Altough we have created a chained error, the error call of the contextual error is not quite right. It mentions the name of the error helper instead of the name of the user-facing function.</p>
<p>If you've read <a href="topic-error-call.html">Including function calls in error messages</a>, you may suspect that we need to pass a <code>call</code> argument to <code><a href="abort.html">abort()</a></code>. That's exactly what needs to happen to fix the call and backtrace issues:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">with_chained_errors</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">expr</span>, <span class="va">call</span> <span class="op">=</span> <span class="fu"><a href="../reference/stack.html">caller_env</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="../reference/try_fetch.html">try_fetch</a></span><span class="op">(</span></span>
<span>    <span class="va">expr</span>,</span>
<span>    error <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">cnd</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="fu"><a href="../reference/abort.html">abort</a></span><span class="op">(</span><span class="st">"Problem during step."</span>, parent <span class="op">=</span> <span class="va">cnd</span>, call <span class="op">=</span> <span class="va">call</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span></code></pre><p></p></div>
<p>Now that we've passed the caller environment as <code>call</code> argument, <code><a href="abort.html">abort()</a></code> automatically picks up the corresponding function call from the execution frame:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="fu">my_verb</span><span class="op">(</span><span class="fu">add</span><span class="op">(</span><span class="fl">1</span>, <span class="st">""</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_verb()`:</span></span>
<span><span class="co">#&gt; ! Problem during step.</span></span>
<span><span class="co">#&gt; Caused by error in `x + y`:</span></span>
<span><span class="co">#&gt; ! non-numeric argument to binary operator</span></span></code></pre><p></p></div><div class="section">
<h3 id="side-note-about-missing-arguments">Side note about missing arguments<a class="anchor" aria-label="anchor" href="#side-note-about-missing-arguments"></a></h3>


<p><code>my_verb()</code> is implemented with a lazy evaluation pattern. The user input kept unevaluated until the error chain context is set up. A downside of this arrangement is that missing argument errors are reported in the wrong context:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="fu">my_verb</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_verb()`:</span></span>
<span><span class="co">#&gt; ! Problem during step.</span></span>
<span><span class="co">#&gt; Caused by error in `my_verb()`:</span></span>
<span><span class="co">#&gt; ! argument "expr" is missing, with no default</span></span></code></pre><p></p></div>
<p>To fix this, simply require these arguments before setting up the chained error context, for instance with the <code><a href="check_required.html">check_required()</a></code> input checker exported from rlang:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">my_verb</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">expr</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="../reference/check_required.html">check_required</a></span><span class="op">(</span><span class="va">expr</span><span class="op">)</span></span>
<span>  <span class="fu">with_chained_errors</span><span class="op">(</span><span class="va">expr</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu">my_verb</span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_verb()`:</span></span>
<span><span class="co">#&gt; ! `expr` is absent but must be supplied.</span></span></code></pre><p></p></div>
</div>

    </div>
    <div class="section level2">
    <h2 id="taking-full-ownership-of-a-causal-error">Taking full ownership of a causal error<a class="anchor" aria-label="anchor" href="#taking-full-ownership-of-a-causal-error"></a></h2>
    <p>It is also possible to completely take ownership of a causal error and rethrow it with a more user-friendly error message. In this case, the original error is completely hidden from the end user. Opting for his approach instead of chaining should be carefully considered because hiding the causal error may deprive users from precious debugging information.</p><ul><li><p>In general, hiding <em>user errors</em> (e.g. dplyr inputs) in this way is likely a bad idea.</p></li>
<li><p>It may be appropriate to hide low-level errors, e.g. replacing HTTP errors by a high-level download error. Similarly, tidyverse packages like dplyr are replacing low-level vctrs errors with higher level errors of their own crafting.</p></li>
<li><p>Hiding causal errors indiscriminately should likely be avoided because it may suppress information about unexpected errors. In general, rethrowing an unchained errors should only be done with specific error classes.</p></li>
</ul><p>To rethrow an error without chaining it, and completely take over the causal error from the user point of view, fetch it with <code><a href="try_fetch.html">try_fetch()</a></code> and throw a new error. The only difference with throwing a chained error is that the <code>parent</code> argument is set to <code>NA</code>. You could also omit the <code>parent</code> argument entirely, but passing <code>NA</code> lets <code><a href="abort.html">abort()</a></code> know it is rethrowing an error from a handler and that it should hide the corresponding error helpers in the backtrace.</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">with_own_scalar_errors</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">expr</span>, <span class="va">call</span> <span class="op">=</span> <span class="fu"><a href="../reference/stack.html">caller_env</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="../reference/try_fetch.html">try_fetch</a></span><span class="op">(</span></span>
<span>    <span class="va">expr</span>,</span>
<span>    vctrs_error_scalar_type <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">cnd</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="fu"><a href="../reference/abort.html">abort</a></span><span class="op">(</span></span>
<span>        <span class="st">"Must supply a vector."</span>,</span>
<span>        parent <span class="op">=</span> <span class="cn">NA</span>,</span>
<span>        error <span class="op">=</span> <span class="va">cnd</span>,</span>
<span>        call <span class="op">=</span> <span class="va">call</span></span>
<span>      <span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">my_verb</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">expr</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="fu"><a href="../reference/check_required.html">check_required</a></span><span class="op">(</span><span class="va">expr</span><span class="op">)</span></span>
<span>  <span class="fu">with_own_scalar_errors</span><span class="op">(</span></span>
<span>    <span class="fu">vctrs</span><span class="fu">::</span><span class="fu"><a href="https://vctrs.r-lib.org/reference/vec_assert.html" class="external-link">vec_assert</a></span><span class="op">(</span><span class="va">expr</span><span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu">my_verb</span><span class="op">(</span><span class="fu"><a href="../reference/env.html">env</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_verb()`:</span></span>
<span><span class="co">#&gt; ! Must supply a vector.</span></span></code></pre><p></p></div>
<p>When a low-level error is overtaken, it is good practice to store it in the high-level error object, so that it can be inspected for debugging purposes. In the snippet above, we stored it in the <code>error</code> field. Here is one way of accessing the original error by subsetting the object returned by <code><a href="last_error.html">last_error()</a></code>:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="fu">rlang</span><span class="fu">::</span><span class="fu"><a href="../reference/last_error.html">last_error</a></span><span class="op">(</span><span class="op">)</span><span class="op">$</span><span class="va">error</span></span></code></pre><p></p></div>
    </div>
    <div class="section level2">
    <h2 id="case-study-mapping-with-chained-errors">Case study: Mapping with chained errors<a class="anchor" aria-label="anchor" href="#case-study-mapping-with-chained-errors"></a></h2>
    <p>One good use case for chained errors is adding information about the iteration state when looping over a set of inputs. To illustrate this, we'll implement a version of <code>map()</code> / <code><a href="https://rdrr.io/r/base/lapply.html" class="external-link">lapply()</a></code> that chains an iteration error to any captured user error.</p>
<p>Here is a minimal implementation of <code>map()</code>:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">my_map</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">.xs</span>, <span class="va">.fn</span>, <span class="va">...</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">out</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/new-vector.html">new_list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">.xs</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html" class="external-link">seq_along</a></span><span class="op">(</span><span class="va">.xs</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="va">out</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu">.fn</span><span class="op">(</span><span class="va">.xs</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span>, <span class="va">...</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span></span>
<span>  <span class="va">out</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">my_map</span><span class="op">(</span><span class="va">add</span>, <span class="fl">100</span><span class="op">)</span></span>
<span><span class="co">#&gt; [[1]]</span></span>
<span><span class="co">#&gt; [1] 101</span></span>
<span><span class="co">#&gt;</span></span>
<span><span class="co">#&gt; [[2]]</span></span>
<span><span class="co">#&gt; [1] 102</span></span></code></pre><p></p></div>
<p>With this implementation, the user has no idea which iteration failed when an error occurs:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="st">"foo"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">my_map</span><span class="op">(</span><span class="va">add</span>, <span class="fl">100</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `x + y`:</span></span>
<span><span class="co">#&gt; ! non-numeric argument to binary operator</span></span></code></pre><p></p></div><div class="section">
<h3 id="rethrowing-with-iteration-information">Rethrowing with iteration information<a class="anchor" aria-label="anchor" href="#rethrowing-with-iteration-information"></a></h3>


<p>To improve on this we'll wrap the loop in a <code><a href="try_fetch.html">try_fetch()</a></code> call that rethrow errors with iteration information. Make sure to call <code><a href="try_fetch.html">try_fetch()</a></code> on the outside of the loop to avoid a massive performance hit:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">my_map</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">.xs</span>, <span class="va">.fn</span>, <span class="va">...</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">out</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/new-vector.html">new_list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">.xs</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">i</span> <span class="op">&lt;-</span> <span class="fl">0L</span></span>
<span></span>
<span>  <span class="fu"><a href="../reference/try_fetch.html">try_fetch</a></span><span class="op">(</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html" class="external-link">seq_along</a></span><span class="op">(</span><span class="va">.xs</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="va">out</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu">.fn</span><span class="op">(</span><span class="va">.xs</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span>, <span class="va">...</span><span class="op">)</span></span>
<span>    <span class="op">}</span>,</span>
<span>    error <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">cnd</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="fu"><a href="../reference/abort.html">abort</a></span><span class="op">(</span></span>
<span>        <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html" class="external-link">sprintf</a></span><span class="op">(</span><span class="st">"Problem while mapping element %d."</span>, <span class="va">i</span><span class="op">)</span>,</span>
<span>        parent <span class="op">=</span> <span class="va">cnd</span></span>
<span>      <span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span>  <span class="va">out</span></span>
<span><span class="op">}</span></span></code></pre><p></p></div>
<p>And that's it, the error chain created by the rethrowing handler now provides users with the number of the failing iteration:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="st">"foo"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">my_map</span><span class="op">(</span><span class="va">add</span>, <span class="fl">100</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_map()`:</span></span>
<span><span class="co">#&gt; ! Problem while mapping element 2.</span></span>
<span><span class="co">#&gt; Caused by error in `x + y`:</span></span>
<span><span class="co">#&gt; ! non-numeric argument to binary operator</span></span></code></pre><p></p></div>
</div>

<div class="section">
<h3 id="dealing-with-errors-thrown-from-the-mapped-function">Dealing with errors thrown from the mapped function<a class="anchor" aria-label="anchor" href="#dealing-with-errors-thrown-from-the-mapped-function"></a></h3>


<p>One problem though, is that the user error call is not very informative when the error occurs immediately in the function supplied to <code>my_map()</code>:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">my_function</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="../reference/scalar-type-predicates.html">is_string</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="../reference/abort.html">abort</a></span><span class="op">(</span><span class="st">"`x` must be a string."</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="st">"foo"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">my_map</span><span class="op">(</span><span class="va">my_function</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_map()`:</span></span>
<span><span class="co">#&gt; ! Problem while mapping element 1.</span></span>
<span><span class="co">#&gt; Caused by error in `.fn()`:</span></span>
<span><span class="co">#&gt; ! `x` must be a string.</span></span></code></pre><p></p></div>
<p>Functions have no names by themselves. Only the variable that refers to the function has a name. In this case, the mapped function is passed by argument to the variable <code>.fn</code>. So, when an error happens, this is the name that is reported to users.</p>
<p>One approach to fix this is to inspect the <code>call</code> field of the error. When we detect a <code>.fn</code> call, we replace it by the defused code supplied as <code>.fn</code> argument:</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="va">my_map</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">.xs</span>, <span class="va">.fn</span>, <span class="va">...</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># Capture the defused code supplied as `.fn`</span></span>
<span>  <span class="va">fn_code</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/substitute.html" class="external-link">substitute</a></span><span class="op">(</span><span class="va">.fn</span><span class="op">)</span></span>
<span></span>
<span>  <span class="va">out</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/new-vector.html">new_list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html" class="external-link">length</a></span><span class="op">(</span><span class="va">.xs</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html" class="external-link">seq_along</a></span><span class="op">(</span><span class="va">.xs</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="fu"><a href="../reference/try_fetch.html">try_fetch</a></span><span class="op">(</span></span>
<span>      <span class="va">out</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu">.fn</span><span class="op">(</span><span class="va">.xs</span><span class="op">[[</span><span class="va">i</span><span class="op">]</span><span class="op">]</span>, <span class="va">...</span><span class="op">)</span>,</span>
<span>      error <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">cnd</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="co"># Inspect the `call` field to detect `.fn` calls</span></span>
<span>        <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="../reference/is_call.html">is_call</a></span><span class="op">(</span><span class="va">cnd</span><span class="op">$</span><span class="va">call</span>, <span class="st">".fn"</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>          <span class="co"># Replace `.fn` by the defused code.</span></span>
<span>          <span class="co"># Keep existing arguments.</span></span>
<span>          <span class="va">cnd</span><span class="op">$</span><span class="va">call</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">fn_code</span></span>
<span>        <span class="op">}</span></span>
<span>        <span class="fu"><a href="../reference/abort.html">abort</a></span><span class="op">(</span></span>
<span>          <span class="fu"><a href="https://rdrr.io/r/base/sprintf.html" class="external-link">sprintf</a></span><span class="op">(</span><span class="st">"Problem while mapping element %s."</span>, <span class="va">i</span><span class="op">)</span>,</span>
<span>          parent <span class="op">=</span> <span class="va">cnd</span></span>
<span>        <span class="op">)</span></span>
<span>      <span class="op">}</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span></span>
<span>  <span class="va">out</span></span>
<span><span class="op">}</span></span></code></pre><p></p></div>
<p>And voilà!</p>
<p></p><div class="sourceCode r"><pre><code><span><span class="fu"><a href="https://rdrr.io/r/base/list.html" class="external-link">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="st">"foo"</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu">my_map</span><span class="op">(</span><span class="va">my_function</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `my_map()`:</span></span>
<span><span class="co">#&gt; ! Problem while mapping element 1.</span></span>
<span><span class="co">#&gt; Caused by error in `my_function()`:</span></span>
<span><span class="co">#&gt; ! `x` must be a string.</span></span></code></pre><p></p></div>
</div>

    </div>

  </main><aside class="col-md-3"><nav id="toc" aria-label="Table of contents"><h2>On this page</h2>
    </nav></aside></div>


   </div>
  <footer><div class="container">
  <div class="pkgdown-footer-left">
  <p>Developed by <a href="https://github.com/lionel-" class="external-link">Lionel Henry</a>, <a href="https://hadley.nz" class="external-link">Hadley Wickham</a>, <a href="https://www.posit.co" class="external-link"><img src="https://www.tidyverse.org/posit-logo.svg" alt="Posit" height="16" width="62" style="margin-bottom: 3px;"></a>.</p>
</div>

<div class="pkgdown-footer-right">
  <p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link">pkgdown</a> 2.1.3.</p>
</div>

  </div></footer></body></html>

